/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    siteTitle: 'Mentalma Therapy',
    siteSubtitle: 'Find the right therapist for your needs',
    selectProfessional: 'Find a Professional',
    chooseTherapist: 'Choose your therapist to see available appointments',
    specialties: 'Specialties',
    selectSpecialty: 'Specialties',
    problemCategories: 'Problem Categories',
    chooseSpecialty: 'Select a specialty area',
    selectDate: 'Select Date & Time',
    chooseSlot: 'Choose an available time slot',
    noSlots: 'No available slots for this professional',
    bookAppointment: 'Book Appointment',
    fullName: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    subject: 'Appointment Subject',
    submitBooking: 'Submit Booking',
    bookingSuccess: 'Appointment Booked Successfully!',
    bookingSuccessMessage: 'You will receive a confirmation email shortly.',
    bookingError: 'Booking Failed',
    bookingErrorMessage: 'Unable to book appointment. Please try again.',
    close: 'Close',
    loading: 'Loading...',
    slotUnavailable: 'This time slot is no longer available. Please choose another.',
    requiredField: 'This field is required',
    signIn: 'Sign In',
    signInRegister: 'Sign in / Register',
    accountMenu: 'Account',
    signedOn: 'Signed on',
    signedOnAs: 'Signed on as',
    aboutAccount: 'About account',
    signOff: 'Sign off',
    chooseSignInOrRegister: 'Sign in or create an account',
    newRegistration: 'New registration',
    signInOption: 'Sign in',
    createAccount: 'Create account',
    emailAlreadyRegistered: 'This email is already registered. Sign in instead.',
    accountUserType: 'Account type',
    clientInfo: 'Client Request Session',
    appointmentCalendar: 'Appointment Calendar',
    professionalList: 'Professional List',
    yourIssues: 'Your Issues',
    filterByClient: 'Filter by Client',
    filterByProblem: 'Filter by Problem',
    clientName: 'Client Name',
    problemKeyword: 'Problem Keyword',
    noAppointments: 'No appointments found for this date',
    professional: 'Professional',
    client: 'Client',
    problemToDiscuss: 'Issue to Discuss',
    clientInfoDescription: 'Submit your information and we will contact you to schedule an appointment',
    preferredDate: 'Preferred Date',
    chooseProfessional: 'Choose a professional',
    issueToDiscuss: 'Issue to Discuss',
    issueDescription: 'Please describe the issue you would like to discuss',
    problemsToDiscuss: 'Issue to Discuss',
    problemsToDiscussTitle: 'Issue I would like to discuss',
    describeYourConcerns: 'Describe what you would like to discuss...',
    improveText: 'AI says: Let me help you explain',
    improveTextHelp: 'AI says: Let me help you explain your concerns more clearly',
    improveWithAI: 'AI says: Let me help you explain',
    improveDescriptionTooltip: 'AI says: Let me help you rewrite your description more clearly',
    aiHelp: 'Let me help you',
    aiHelpSpecialty: 'Let me help you choose a specialty',
    aiHelpProblems: 'Let me help you select problems',
    aiHelpProfessional: 'Let me help you find a professional',
    aiFillAllTitle: 'AI says: Let me help you',
    aiFillAllButton: 'Let me help you fill this form',
    aiFillAllReady: 'Ready. Click and I will suggest specialty, counseling type, and professional.',
    aiFillAllNeedIssue: 'First describe what you want to discuss below, then I can help.',
    welcomeUser: 'Welcome',
    specialtyDesired: 'Specialty Desired',
    autoSelectSpecialty: 'Auto-select specialty based on problems',
    findProfessional: 'Find a Professional',
    browseProfessionals: 'Browse all professionals alphabetically',
    findProfessionalAI: 'Find best match using AI',
    aiRecommendation: 'AI Recommendation',
    suggestSpecialties: 'Suggest Specialties',
    suggestSpecialtiesHelp: 'Use the AI button to get specialty suggestions based on your concerns',
    suggestedSpecialties: 'Suggested Specialties',
    processing: 'Processing...',
    aiError: 'AI request failed. Please try again.',
    submitRequest: 'Submit Request',
    requestSuccess: 'Request Submitted Successfully!',
    requestSuccessMessage: 'Your request has been submitted and a confirmation email has been sent. We will contact you soon to schedule your appointment.',
    requestError: 'Submission Failed',
    requestErrorMessage: 'Unable to submit request. Please try again.',
    signInDescription: 'Create your account to access our services',
    username: 'Username',
    usernamePlaceholder: 'Choose a username',
    saveUser: 'Save',
    userSuccess: 'User Created Successfully!',
    userSuccessMessage: 'Your account has been created.',
    userError: 'Registration Failed',
    userErrorMessage: 'Unable to create user. Please try again.',
    availability: 'Availability Calendar',
    availableSlots: 'Available',
    bookedSlots: 'Booked',
    noSlotsAvailable: 'No time slots available for this date',
    available: 'Available',
    booked: 'Booked',
    adminPanel: 'Admin Panel',
    adminPanelDescription: 'View and edit database records',
    adminWarning: 'Warning: Deleted rows cannot be recovered',
    specialtiesTab: 'Manage Specialties',
    resumes: 'Resumes',
    usersTable: 'Users',
    appointmentsTable: 'Appointments',
    clientRequestsTable: 'Client Requests',
    availableSlotsTable: 'Available Slots',
    specialtiesTable: 'Specialties',
    professionalsTable: 'Professionals',
    resumesTable: 'Resumes',
    sessionsTable: 'Sessions',
    paymentTransactionsTable: 'Payment Transactions',
    counselingTypesTable: 'Counseling Types',
    sessionPricesTable: 'Session Prices',
    standardQuestionnairesTable: 'Std Questionnaires',
    problemsTable: 'Problems',
    consultLogTable: 'Consult Log',
    questionnaireResultsTable: 'Questionnaire Results',
    professionsTable: 'Professions',
    eventsMasterTable: 'Events / Match Results',
    professions: 'Professions',
    manageProfessions: 'Manage Professions',
    profession: 'Profession',
    addProfession: 'Add Profession',
    editProfession: 'Edit Profession',
    noProfessions: 'No professions found',
    professionName: 'Profession Name',
    selectProfession: 'Select Profession',
    allProfessions: 'All Professions',
    selectActiveProfession: 'Select Active Profession',
    activeProfessionLabel: 'Active Profession',
    professionRequired: 'Profession is required',
    deleteUsersDescription: 'Remove all registered users from the system',
    deleteUsersWarning: 'This will permanently delete all user accounts',
    deleteAppointmentsDescription: 'Remove all appointment records',
    deleteAppointmentsWarning: 'This will permanently delete all booked appointments',
    deleteClientRequestsDescription: 'Remove all client request submissions',
    deleteClientRequestsWarning: 'This will permanently delete all pending requests',
    deleteAvailableSlotsDescription: 'Remove all available time slots',
    deleteAvailableSlotsWarning: 'This will permanently delete all professional availability',
    deleteAllRows: 'Delete All Rows',
    confirmDelete: 'Confirm Delete',
    confirmDeleteMessage: 'Are you absolutely sure you want to delete all rows from:',
    typeDeleteToConfirm: 'Type "DELETE" to confirm this action:',
    cancel: 'Cancel',
    discardChanges: 'Discard changes',
    deleting: 'Deleting...',
    confirmDeleteAction: 'Confirm Delete',
    deleteSuccess: 'Data Deleted Successfully',
    deleteSuccessMessage: 'All rows have been deleted from the table',
    deleteError: 'Delete Failed',
    deleteErrorMessage: 'Unable to delete data. Please try again.',
    dataBrowser: 'Data Browser',
    dataBrowserDescription: 'View, edit, and delete individual rows from database tables',
    schedules: 'Schedules',
    selectTable: 'Select Table',
    filterByUser: 'Filter by User',
    userFilterPlaceholder: 'Search by name or email',
    search: 'Search',
    noDataFound: 'No data found',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    confirmShort: 'Confirm',
    updateSuccess: 'Row Updated Successfully',
    updateSuccessMessage: 'The row has been updated',
    updateError: 'Update Failed',
    updateErrorMessage: 'Unable to update row. Please try again.',
    rowDeleteSuccess: 'Row Deleted Successfully',
    rowDeleteSuccessMessage: 'The row has been deleted',
    rowDeleteError: 'Delete Failed',
    rowDeleteErrorMessage: 'Unable to delete row. Please try again.',
    askMari: 'Ask MarI',
    ai: 'AI',
    // askMariForProfessional: 'Ask MarI for Professional',
    deleteSpecialtiesDescription: 'Remove all therapy specialties from the database',
    deleteSpecialtiesWarning: 'This will delete all specialties. The "Your Issues" menu will be empty until new specialties are added.',
    aboutUs: 'About Us',
    help: 'Help',
    ourMission: 'Our Mission – MENTALMA',
    ourMissionText:
      'At MENTALMA, we are on a mission to transform the way you experience mental health. We help you reconnect with your most benevolent thoughts and your inner intuition, creating a safe and supportive space where you can truly listen to yourself. Together with caring, licensed professionals, we guide you toward emotional balance, personal growth, and a higher quality of life.',
    ourVision: 'Our Vision',
    ourVisionText:
      'We envision MENTALMA as a space where, the moment you enter, you begin a journey of inner discovery and conscious growth—in the company of dedicated wellness professionals who guide and support you every step of the way.',
    ourVisionText2:
      'A place that empowers you to keep evolving through self-awareness and intuition, while helping create a world where mental health and well-being are accessible to all.',
    ourVisionText3:
      'A world where everyone feels empowered to choose self-love as a path to heal, grow, and live a more meaningful and balanced life.',
    ourValues: 'Our Values',
    professionalismTitle: 'Professionalism',
    professionalismText:
      'You\'re in safe hands. Our licensed professionals bring years of experience and are here to support you with care, trust, and dedication.',
    compassionTitle: 'Compassion',
    compassionText:
      'We meet you with kindness, empathy, and respect—creating a space where you can feel truly understood.',
    confidentialityTitle: 'Confidentiality',
    confidentialityText:
      'Your privacy matters deeply to us. Everything you share stays safe and confidential, so you can open up with ease.',
    artificialIntelligenceTitle: 'Artificial Intelligence',
    artificialIntelligenceText:
      'We use AI to facilitate the use of our platform and to recommend choices for our clients. We do not try to replace the professional\'s advice but rather use AI to help the professionals evaluate and solve your issues.',
    excellenceTitle: 'Excellence',
    excellenceText:
      'We\'re committed to giving you the best possible care, always learning and growing to support you in the most meaningful way.',
    autonomyTitle: 'Autonomy',
    autonomyText:
      'We empower you to trust yourself, make your own choices, and grow at your own pace—supporting you in building the confidence and clarity to lead your own journey.',
    ourTeam: 'Our Team',
    ourTeamText:
      'MENTALMA was founded by a Colombian psychologist Maria Jose Agresott and an American Chief Scientist David E Brown, combining human insight and technology to make mental health care more accessible.',
    ourTeamText2:
      'Together with a dedicated team of wellness professionals, we create a supportive space where professional care meets genuine human connection—helping you grow, heal, and reconnect with yourself.',
    gettingStarted: 'Getting Started',
    helpUsersAndRolesTitle: 'Users and Roles',
    helpRoleNoUserLabel: 'No user',
    helpRoleNoUserText:
      'Some functions are available to guests who are not signed in, such as viewing professionals, the About page, and this Help page. These options appear in the main menu when no user is signed in.',
    helpRoleClientsLabel: 'Clients',
    helpRoleClientsText:
      'Clients can request a session. If no user is signed in, requesting a session will first take the person to the sign-in and create-user screen.',
    helpRoleProfessionalsLabel: 'Professionals',
    helpRoleProfessionalsText:
      'Professionals and administrators will see a Book Session option that shows requested sessions for a professional, or a list of professionals for administrators. From there they can confirm a session, which creates a Google Meet calendar entry and sends email notifications to both the professional and the client.',
    helpRoleAdministratorsLabel: 'Administrators',
    helpRoleAdministratorsText:
      'Administrators also see additional configuration options. When a client requests a session, it appears in the Requests list and cannot be confirmed until a professional or administrator reviews and confirms it in Book Sessions.',
    howToBookQuestion: 'How do I book an appointment?',
    howToBookAnswer: 'Simply browse our list of professionals, select one that matches your needs, choose an available time slot, and fill out the booking form. You\'ll receive a confirmation email within a few minutes.',
    firstSessionQuestion: 'What should I expect in my first session?',
    firstSessionAnswer: 'Your first session is an opportunity to get to know your professional and discuss your goals. They\'ll ask questions to understand your needs and create a personalized treatment plan.',
    appointments: 'Appointments',
    cancelAppointmentQuestion: 'Can I cancel or reschedule my appointment?',
    cancelAppointmentAnswer: 'Yes, you can cancel or reschedule up to 24 hours before your appointment. Please contact us as soon as possible to make changes.',
    rescheduleQuestion: 'How do I reschedule an appointment?',
    rescheduleAnswer: 'Contact our support team via email or phone, and we\'ll help you find a new time that works for you.',
    sessionLengthQuestion: 'How long is each session?',
    sessionLengthAnswer: 'Standard sessions are 50 minutes long. Some professionals also offer extended 90-minute sessions for more intensive work.',
    payments: 'Payments',
    paymentMethodsQuestion: 'What payment methods do you accept?',
    paymentMethodsAnswer: 'We accept all major credit cards, debit cards, and some insurance plans. Payment is due at the time of booking.',
    insuranceQuestion: 'Do you accept insurance?',
    insuranceAnswer: 'We work with many major insurance providers. Please contact us with your insurance information, and we\'ll verify your coverage.',
    privacy: 'Privacy & Security',
    confidentialityQuestion: 'How confidential are my sessions?',
    confidentialityAnswer: 'All sessions are completely confidential. Your professional is bound by professional ethics and legal requirements to protect your privacy. Information is only shared with your explicit consent or in cases where there is a risk of harm.',
    dataSecurityQuestion: 'How is my personal data protected?',
    dataSecurityAnswer: 'We use industry-standard encryption and security measures to protect your personal information. Our platform complies with HIPAA regulations and all applicable privacy laws.',
    needMoreHelp: 'Need More Help?',
    contactSupport: 'If you have questions not covered here, our support team is here to help.',
    supportPhone: 'Phone',
    supportHours: 'Hours',
    supportHoursValue: 'Monday - Friday, 9:00 AM - 6:00 PM EST',
    bookSession: 'Book Session',
    submitResume: 'Work With Us',
    applicationContents: 'Application Contents',
    payment: 'Make a Payment',
    allSpecialties: 'All Specialties',
    clearFilter: 'Clear Filter',
    explainField: 'Explain this field',
    fieldExplanation: 'Field Explanation',
    explainSpecialty: 'Explain',
    pleaseSelectSpecialty: 'Please select a specialty first',
    welcomeTitle: 'Welcome to Professional Therapy Services',
    signInRequired: 'Please sign in with your Google account to access our services',
    signInWithGoogle: 'Sign in with Google',
    error: 'Error',
    signInSuccess: 'Welcome Back',
    signInSuccessMessage: 'You have successfully signed in',
    signedOut: 'Signed Out',
    signedOutMessage: 'You have been signed out successfully',
    signOutError: 'Sign Out Error',
    home: 'Home',
    welcomeHome: 'Welcome to Professional Therapy Services',
    homeDescription: 'We connect you with licensed mental health professionals who care about your well-being. Our AI-powered platform helps you find the perfect therapist match for your unique needs.',
    homeFeature1Title: 'Expert Professionals',
    homeFeature1Description: 'Access our network of licensed professionals specializing in various areas of mental health.',
    homeFeature2Title: 'AI-Powered Matching',
    homeFeature2Description: 'Our intelligent assistant, MarI, helps you find the therapist best suited to your needs.',
    homeFeature3Title: 'Easy Scheduling',
    homeFeature3Description: 'Book appointments online at your convenience and manage your sessions effortlessly.',
    homeGetStarted: 'Ready to Begin Your Journey?',
    homeGetStartedDescription: 'Explore our professional directory, submit a request, or let our AI assistant guide you to the right professional.',
    'Complete Your Profile': 'Complete Your Profile',
    'Please complete your profile to continue using the application.': 'Please complete your profile to continue using the application.',
    'Username': 'Username',
    'Enter a unique username': 'Enter a unique username',
    'Full Name': 'Full Name',
    'Enter your full name': 'Enter your full name',
    'Email': 'Email',
    'Phone': 'Phone',
    'Enter your phone number (optional)': 'Enter your phone number (optional)',
    'Creating Profile...': 'Creating Profile...',
    'Complete Profile': 'Complete Profile',
    addRecord: '+ Add Record',
    timeZone: 'Time Zone',
    manageProfessionals: 'Manage Professionals',
    counselingTypes: 'Counseling Types',
    languages: 'Languages',
    problems: 'Problems',
    selected: 'selected',
    clear: 'Clear',
    suggestProblems: 'Suggest Problems',
    rightClickInfoTitle: 'AI Information',
    rightClickInfoHint: 'Right-click any specialty, problem, or counseling type for AI details',
    rightClickInfoLoading: 'Generating information...',
    rightClickInfoClose: 'Close',
    rightClickSpecialtyHint: 'Right-click to learn more about this specialty',
    rightClickProblemHint: 'Right-click to learn more about this problem',
    rightClickCounselingHint: 'Right-click to learn more about this counseling type',
    learnMore: 'Learn more about',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot / Change Password',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    resetEmailSent: 'Password reset email sent! Check your inbox.',
    newPassword: 'New Password',
    passwordMinLength: 'Password must be at least 8 characters',
    passwordMismatch: 'Passwords do not match',
    invalidCredentials: 'Invalid email or password',
    setYourPassword: 'Set Your Password',
    passwordUpdated: 'Password updated successfully!',
    checkYourEmail: 'Check your email for the reset link',
    backToSignIn: 'Back to Sign In',
    signInWithEmail: 'Sign in with email and password',
    createAccountWithPassword: 'Create account with email and password',
    enterPassword: 'Enter your password',
    enterNewPassword: 'Enter a new password',
    confirmNewPassword: 'Confirm your new password',
  },
  es: {
    siteTitle: 'Mentalma Terapia',
    siteSubtitle: 'Encuentra el terapeuta adecuado para tus necesidades',
    selectProfessional: 'Encontrar un Profesional',
    chooseTherapist: 'Elija su terapeuta para ver las citas disponibles',
    specialties: 'Especialidades',
    selectSpecialty: 'Especialidades',
    problemCategories: 'Categorías de Problemas',
    chooseSpecialty: 'Seleccione un área de especialidad',
    selectDate: 'Seleccione Fecha y Hora',
    chooseSlot: 'Elija un horario disponible',
    noSlots: 'No hay horarios disponibles para este profesional',
    bookAppointment: 'Reservar Cita',
    fullName: 'Nombre Completo',
    email: 'Correo Electrónico',
    phone: 'Número de Teléfono',
    subject: 'Motivo de la Cita',
    submitBooking: 'Enviar Reserva',
    bookingSuccess: '¡Cita Reservada Exitosamente!',
    bookingSuccessMessage: 'Recibirá un correo de confirmación en breve.',
    bookingError: 'Error al Reservar',
    bookingErrorMessage: 'No se pudo reservar la cita. Por favor, intente de nuevo.',
    close: 'Cerrar',
    loading: 'Cargando...',
    slotUnavailable: 'Este horario ya no está disponible. Por favor, elija otro.',
    requiredField: 'Este campo es obligatorio',
    signIn: 'Iniciar Sesión',
    signInRegister: 'Iniciar sesión / Registrarse',
    accountMenu: 'Cuenta',
    signedOn: 'Conectado',
    signedOnAs: 'Sesión iniciada como',
    aboutAccount: 'Acerca de la cuenta',
    signOff: 'Cerrar sesión',
    chooseSignInOrRegister: 'Iniciar sesión o crear una cuenta',
    newRegistration: 'Nuevo registro',
    signInOption: 'Iniciar sesión',
    createAccount: 'Crear cuenta',
    emailAlreadyRegistered: 'Este correo ya está registrado. Inicie sesión.',
    accountUserType: 'Tipo de cuenta',
    clientInfo: 'Solicitar Sesión',
    appointmentCalendar: 'Calendario de Citas',
    professionalList: 'Lista de Profesionales',
    yourIssues: 'Sus Problemas',
    filterByClient: 'Filtrar por Cliente',
    filterByProblem: 'Filtrar por Problema',
    clientName: 'Nombre del Cliente',
    problemKeyword: 'Palabra Clave del Problema',
    noAppointments: 'No se encontraron citas para esta fecha',
    professional: 'Profesional',
    client: 'Cliente',
    problemToDiscuss: 'Asunto a Discutir',
    clientInfoDescription: 'Envíe su información y nos pondremos en contacto para programar una cita',
    preferredDate: 'Fecha Preferida',
    chooseProfessional: 'Elija un profesional',
    issueToDiscuss: 'Asunto a Discutir',
    issueDescription: 'Por favor, describa el asunto que le gustaría discutir',
    problemsToDiscuss: 'Asunto a Discutir',
    problemsToDiscussTitle: 'Asunto que me gustaría discutir',
    describeYourConcerns: 'Describa lo que le gustaría discutir...',
    improveText: 'La IA dice: Déjame ayudarte a explicar',
    improveTextHelp: 'La IA dice: Déjame ayudarte a explicar tus preocupaciones con más claridad',
    improveWithAI: 'La IA dice: Déjame ayudarte a explicar',
    improveDescriptionTooltip: 'La IA dice: Déjame ayudarte a reescribir tu descripción con más claridad',
    aiHelp: 'Déjame ayudarte',
    aiHelpSpecialty: 'Déjame ayudarte a elegir una especialidad',
    aiHelpProblems: 'Déjame ayudarte a seleccionar problemas',
    aiHelpProfessional: 'Déjame ayudarte a encontrar un profesional',
    aiFillAllTitle: 'La IA dice: Déjame ayudarte',
    aiFillAllButton: 'Déjame ayudarte a completar este formulario',
    aiFillAllReady: 'Listo. Haz clic y te sugeriré especialidad, tipo de consejería y profesional.',
    aiFillAllNeedIssue: 'Primero describe qué quieres tratar abajo, y luego podré ayudarte.',
    welcomeUser: 'Bienvenido/a',
    specialtyDesired: 'Especialidad Deseada',
    autoSelectSpecialty: 'Auto-seleccionar especialidad basada en problemas',
    findProfessional: 'Encontrar un Profesional',
    browseProfessionals: 'Explorar todos los profesionales alfabéticamente',
    findProfessionalAI: 'Encontrar mejor coincidencia usando IA',
    aiRecommendation: 'Recomendación de IA',
    suggestSpecialties: 'Sugerir Especialidades',
    suggestSpecialtiesHelp: 'Use el botón de IA para obtener sugerencias de especialidades basadas en sus preocupaciones',
    suggestedSpecialties: 'Especialidades Sugeridas',
    processing: 'Procesando...',
    aiError: 'La solicitud de IA falló. Por favor, intente de nuevo.',
    submitRequest: 'Enviar Solicitud',
    requestSuccess: '¡Solicitud Enviada Exitosamente!',
    requestSuccessMessage: 'Su solicitud ha sido enviada y se ha enviado un correo electrónico de confirmación. Nos pondremos en contacto pronto para programar su cita.',
    requestError: 'Error al Enviar',
    requestErrorMessage: 'No se pudo enviar la solicitud. Por favor, intente de nuevo.',
    signInDescription: 'Cree su cuenta para acceder a nuestros servicios',
    username: 'Nombre de Usuario',
    usernamePlaceholder: 'Elija un nombre de usuario',
    saveUser: 'Guardar',
    userSuccess: '¡Usuario Creado Exitosamente!',
    userSuccessMessage: 'Su cuenta ha sido creada.',
    userError: 'Error en el Registro',
    userErrorMessage: 'No se pudo crear el usuario. Por favor, intente de nuevo.',
    availability: 'Calendario de Disponibilidad',
    availableSlots: 'Disponibles',
    bookedSlots: 'Reservados',
    noSlotsAvailable: 'No hay horarios disponibles para esta fecha',
    available: 'Disponible',
    booked: 'Reservado',
    adminPanel: 'Panel de Administración',
    adminPanelDescription: 'Ver y editar registros de base de datos',
    adminWarning: 'Advertencia: Las filas eliminadas no se pueden recuperar',
    specialtiesTab: 'Gestionar Especialidades',
    resumes: 'Currículums',
    usersTable: 'Usuarios',
    appointmentsTable: 'Citas',
    clientRequestsTable: 'Solicitudes de Clientes',
    availableSlotsTable: 'Horarios Disponibles',
    specialtiesTable: 'Especialidades',
    professionalsTable: 'Profesionales',
    resumesTable: 'Currículums',
    sessionsTable: 'Sesiones',
    paymentTransactionsTable: 'Transacciones de Pago',
    counselingTypesTable: 'Tipos de Consejeria',
    sessionPricesTable: 'Precios de Sesiones',
    standardQuestionnairesTable: 'Cuestionarios estándar',
    problemsTable: 'Problemas',
    consultLogTable: 'Registro de Consultas',
    questionnaireResultsTable: 'Resultados de Cuestionarios',
    professionsTable: 'Profesiones',
    eventsMasterTable: 'Eventos / Resultados',
    professions: 'Profesiones',
    manageProfessions: 'Gestionar Profesiones',
    profession: 'Profesión',
    addProfession: 'Agregar Profesión',
    editProfession: 'Editar Profesión',
    noProfessions: 'No se encontraron profesiones',
    professionName: 'Nombre de Profesión',
    selectProfession: 'Seleccionar Profesión',
    allProfessions: 'Todas las Profesiones',
    selectActiveProfession: 'Seleccionar Profesión Activa',
    activeProfessionLabel: 'Profesión Activa',
    professionRequired: 'La profesión es requerida',
    deleteUsersDescription: 'Eliminar todos los usuarios registrados del sistema',
    deleteUsersWarning: 'Esto eliminará permanentemente todas las cuentas de usuario',
    deleteAppointmentsDescription: 'Eliminar todos los registros de citas',
    deleteAppointmentsWarning: 'Esto eliminará permanentemente todas las citas reservadas',
    deleteClientRequestsDescription: 'Eliminar todas las solicitudes de clientes enviadas',
    deleteClientRequestsWarning: 'Esto eliminará permanentemente todas las solicitudes pendientes',
    deleteAvailableSlotsDescription: 'Eliminar todos los horarios disponibles',
    deleteAvailableSlotsWarning: 'Esto eliminará permanentemente toda la disponibilidad de profesionales',
    deleteAllRows: 'Eliminar Todas las Filas',
    confirmDelete: 'Confirmar Eliminación',
    confirmDeleteMessage: '¿Está absolutamente seguro de que desea eliminar todas las filas de:',
    typeDeleteToConfirm: 'Escriba "DELETE" para confirmar esta acción:',
    cancel: 'Cancelar',
    discardChanges: 'Descartar cambios',
    deleting: 'Eliminando...',
    confirmDeleteAction: 'Confirmar Eliminación',
    deleteSuccess: 'Datos Eliminados Exitosamente',
    deleteSuccessMessage: 'Todas las filas han sido eliminadas de la tabla',
    deleteError: 'Error al Eliminar',
    deleteErrorMessage: 'No se pudieron eliminar los datos. Por favor, intente de nuevo.',
    dataBrowser: 'Explorador de Datos',
    dataBrowserDescription: 'Ver, editar y eliminar filas individuales de las tablas de la base de datos',
    schedules: 'Horarios',
    selectTable: 'Seleccionar Tabla',
    filterByUser: 'Filtrar por Usuario',
    userFilterPlaceholder: 'Buscar por nombre o correo',
    search: 'Buscar',
    noDataFound: 'No se encontraron datos',
    actions: 'Acciones',
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    confirmShort: 'Confirmar',
    updateSuccess: 'Fila Actualizada Exitosamente',
    updateSuccessMessage: 'La fila ha sido actualizada',
    updateError: 'Error al Actualizar',
    updateErrorMessage: 'No se pudo actualizar la fila. Por favor, intente de nuevo.',
    rowDeleteSuccess: 'Fila Eliminada Exitosamente',
    rowDeleteSuccessMessage: 'La fila ha sido eliminada',
    rowDeleteError: 'Error al Eliminar',
    rowDeleteErrorMessage: 'No se pudo eliminar la fila. Por favor, intente de nuevo.',
    askMari: 'Preguntar a MarI',
    ai: 'IA',
   // askMariForProfessional: 'Preguntar a MarI por Profesional',
    deleteSpecialtiesDescription: 'Eliminar todas las especialidades de terapia de la base de datos',
    deleteSpecialtiesWarning: 'Esto eliminará todas las especialidades. El menú "Tus Problemas" estará vacío hasta que se agreguen nuevas especialidades.',
    aboutUs: 'Acerca de Nosotros',
    help: 'Ayuda',
    ourMission: 'Nuestra Misión – MENTALMA',
    ourMissionText:
      'En MENTALMA tenemos la misión de transformar la forma en que vive la salud mental. Le ayudamos a reconectar con sus pensamientos más benevolos y con su intuición interior, creando un espacio seguro y de apoyo donde pueda escucharse de verdad. Junto a profesionales titulados y cercanos, le orientamos hacia el equilibrio emocional, el crecimiento personal y una mayor calidad de vida.',
    ourVision: 'Nuestra Visión',
    ourVisionText:
      'Imaginamos MENTALMA como un espacio donde, desde el momento en que entra, inicia un camino de descubrimiento interior y crecimiento consciente—acompañado por profesionales del bienestar dedicados que le guían y apoyan en cada paso.',
    ourVisionText2:
      'Un lugar que le impulsa a seguir evolucionando mediante la autoconciencia y la intuición, y que contribuye a un mundo donde la salud mental y el bienestar sean accesibles para todas las personas.',
    ourVisionText3:
      'Un mundo donde cada persona se sienta empoderada para elegir el amor propio como camino para sanar, crecer y vivir una vida más plena y equilibrada.',
    ourValues: 'Nuestros Valores',
    professionalismTitle: 'Profesionalismo',
    professionalismText:
      'Está en buenas manos. Nuestros profesionales titulados aportan años de experiencia y están aquí para acompañarle con cuidado, confianza y dedicación.',
    compassionTitle: 'Compasión',
    compassionText:
      'Le recibimos con amabilidad, empatía y respeto—creando un espacio donde pueda sentirse verdaderamente comprendido.',
    confidentialityTitle: 'Confidencialidad',
    confidentialityText:
      'Su privacidad nos importa profundamente. Todo lo que comparte permanece seguro y confidencial, para que pueda abrirse con tranquilidad.',
    artificialIntelligenceTitle: 'Inteligencia artificial',
    artificialIntelligenceText:
      'Utilizamos la IA para facilitar el uso de nuestra plataforma y para recomendar opciones a nuestros clientes. No pretendemos sustituir el criterio del profesional, sino apoyarle para evaluar y abordar sus inquietudes.',
    excellenceTitle: 'Excelencia',
    excellenceText:
      'Nos comprometemos a ofrecerle la mejor atención posible, aprendiendo y creciendo de forma continua para acompañarle de la manera más significativa.',
    autonomyTitle: 'Autonomía',
    autonomyText:
      'Le fortalecemos para confiar en usted mismo, tomar sus propias decisiones y crecer a su ritmo—apoyándole a desarrollar la confianza y la claridad para liderar su propio camino.',
    ourTeam: 'Nuestro Equipo',
    ourTeamText:
      'MENTALMA fue fundada por la psicóloga colombiana Maria Jose Agresott y el científico jefe estadounidense David E Brown, uniendo la mirada humana y la tecnología para acercar la atención en salud mental.',
    ourTeamText2:
      'Junto a un equipo dedicado de profesionales del bienestar, creamos un espacio de apoyo donde el cuidado profesional se encuentra con la conexión humana genuina—ayudándole a crecer, sanar y reconectarse consigo mismo.',
    gettingStarted: 'Comenzando',
    howToBookQuestion: '¿Cómo reservo una cita?',
    howToBookAnswer: 'Simplemente navegue por nuestra lista de profesionales, seleccione uno que coincida con sus necesidades, elija un horario disponible y complete el formulario de reserva. Recibirá un correo de confirmación en unos minutos.',
    firstSessionQuestion: '¿Qué debo esperar en mi primera sesión?',
    firstSessionAnswer: 'Su primera sesión es una oportunidad para conocer a su profesional y discutir sus objetivos. Harán preguntas para entender sus necesidades y crear un plan de tratamiento personalizado.',
    appointments: 'Citas',
    cancelAppointmentQuestion: '¿Puedo cancelar o reprogramar mi cita?',
    cancelAppointmentAnswer: 'Sí, puede cancelar o reprogramar hasta 24 horas antes de su cita. Por favor contáctenos lo antes posible para hacer cambios.',
    rescheduleQuestion: '¿Cómo reprogramo una cita?',
    rescheduleAnswer: 'Contacte a nuestro equipo de soporte por correo electrónico o teléfono, y lo ayudaremos a encontrar un nuevo horario que funcione para usted.',
    sessionLengthQuestion: '¿Cuánto dura cada sesión?',
    sessionLengthAnswer: 'Las sesiones estándar duran 50 minutos. Algunos profesionales también ofrecen sesiones extendidas de 90 minutos para trabajo más intensivo.',
    payments: 'Pagos',
    paymentMethodsQuestion: '¿Qué métodos de pago aceptan?',
    paymentMethodsAnswer: 'Aceptamos todas las principales tarjetas de crédito, tarjetas de débito y algunos planes de seguro. El pago se debe al momento de la reserva.',
    insuranceQuestion: '¿Aceptan seguro?',
    insuranceAnswer: 'Trabajamos con muchos proveedores de seguros importantes. Por favor contáctenos con su información de seguro y verificaremos su cobertura.',
    privacy: 'Privacidad y Seguridad',
    confidentialityQuestion: '¿Qué tan confidenciales son mis sesiones?',
    confidentialityAnswer: 'Todas las sesiones son completamente confidenciales. Su profesional está obligado por la ética profesional y requisitos legales a proteger su privacidad. La información solo se comparte con su consentimiento explícito o en casos donde hay riesgo de daño.',
    dataSecurityQuestion: '¿Cómo se protegen mis datos personales?',
    dataSecurityAnswer: 'Utilizamos encriptación estándar de la industria y medidas de seguridad para proteger su información personal. Nuestra plataforma cumple con las regulaciones HIPAA y todas las leyes de privacidad aplicables.',
    needMoreHelp: '¿Necesita Más Ayuda?',
    contactSupport: 'Si tiene preguntas no cubiertas aquí, nuestro equipo de soporte está aquí para ayudar.',
    supportPhone: 'Teléfono',
    supportHours: 'Horario',
    supportHoursValue: 'Lunes - Viernes, 9:00 AM - 6:00 PM EST',
    bookSession: 'Reservar Sesión',
    submitResume: 'Trabaja Con Nosotros',
    applicationContents: 'Contenido de la Solicitud',
    payment: 'Hacer un Pago',
    askMariForSpecialty: 'Déjame ayudarte a elegir una especialidad',
    allSpecialties: 'Todas las Especialidades',
    clearFilter: 'Limpiar Filtro',
    explainField: 'Explicar este campo',
    fieldExplanation: 'Explicación del Campo',
    explainSpecialty: 'Explicar',
    pleaseSelectSpecialty: 'Por favor seleccione una especialidad primero',
    welcomeTitle: 'Bienvenido a Servicios de Terapia Profesional',
    signInRequired: 'Por favor inicie sesión con su cuenta de Google para acceder a nuestros servicios',
    signInWithGoogle: 'Iniciar sesión con Google',
    error: 'Error',
    signInSuccess: 'Bienvenido de Nuevo',
    signInSuccessMessage: 'Ha iniciado sesión exitosamente',
    signedOut: 'Sesión Cerrada',
    signedOutMessage: 'Ha cerrado sesión exitosamente',
    signOutError: 'Error al Cerrar Sesión',
    home: 'Inicio',
    welcomeHome: 'Bienvenido a Servicios de Terapia Profesional',
    homeDescription: 'Le conectamos con profesionales de salud mental licenciados que se preocupan por su bienestar. Nuestra plataforma impulsada por IA le ayuda a encontrar el terapeuta perfecto para sus necesidades únicas.',
    homeFeature1Title: 'Profesionales Expertos',
    homeFeature1Description: 'Acceda a nuestra red de profesionales licenciados especializados en diversas áreas de salud mental.',
    homeFeature2Title: 'Emparejamiento con IA',
    homeFeature2Description: 'Nuestra asistente inteligente, MarI, le ayuda a encontrar el terapeuta más adecuado para sus necesidades.',
    homeFeature3Title: 'Programación Fácil',
    homeFeature3Description: 'Reserve citas en línea a su conveniencia y gestione sus sesiones sin esfuerzo.',
    homeGetStarted: '¿Listo para Comenzar su Viaje?',
    homeGetStartedDescription: 'Explore nuestro directorio de profesionales, envíe una solicitud o deje que nuestra asistente de IA le guíe al profesional adecuado.',
    // (kept as existing canonical translation key)
    helpUsersAndRolesTitle: 'Usuarios y Roles',
    helpRoleNoUserLabel: 'Sin usuario',
    helpRoleNoUserText:
      'Algunas funciones están disponibles para invitados que no han iniciado sesión, como ver profesionales, la página “Acerca de” y esta página de Ayuda. Estas opciones aparecen en el menú principal cuando no hay un usuario autenticado.',
    helpRoleClientsLabel: 'Clientes',
    helpRoleClientsText:
      'Los clientes pueden solicitar una sesión. Si no hay un usuario autenticado, solicitar una sesión primero llevará a la persona a la pantalla de iniciar sesión y crear usuario.',
    helpRoleProfessionalsLabel: 'Profesionales',
    helpRoleProfessionalsText:
      'Los profesionales y administradores verán una opción de “Reservar sesión” que muestra las sesiones solicitadas para un profesional, o una lista de profesionales para administradores. Desde allí pueden confirmar una sesión, lo que crea una entrada de Google Meet en el calendario y envía notificaciones por correo electrónico tanto al profesional como al cliente.',
    helpRoleAdministratorsLabel: 'Administradores',
    helpRoleAdministratorsText:
      'Los administradores también ven opciones adicionales de configuración. Cuando un cliente solicita una sesión, aparece en la lista de Solicitudes y no puede confirmarse hasta que un profesional o administrador la revise y la confirme en “Reservar sesión”.',
    'Complete Your Profile': 'Complete su Perfil',
    'Please complete your profile to continue using the application.': 'Por favor complete su perfil para continuar usando la aplicación.',
    'Username': 'Nombre de Usuario',
    'Enter a unique username': 'Ingrese un nombre de usuario único',
    'Full Name': 'Nombre Completo',
    'Enter your full name': 'Ingrese su nombre completo',
    'Email': 'Correo Electrónico',
    'Phone': 'Teléfono',
    'Enter your phone number (optional)': 'Ingrese su número de teléfono (opcional)',
    'Creating Profile...': 'Creando Perfil...',
    'Complete Profile': 'Completar Perfil',
    addRecord: '+ Agregar Registro',
    timeZone: 'Zona Horaria',
    manageProfessionals: 'Gestionar Profesionales',
    counselingTypes: 'Tipos de Consejería',
    languages: 'Idiomas',
    problems: 'Problemas',
    selected: 'seleccionado(s)',
    clear: 'Limpiar',
    suggestProblems: 'Sugerir Problemas',
    rightClickInfoTitle: 'Información de IA',
    rightClickInfoHint: 'Clic derecho en una especialidad, problema o tipo de consejería para ver detalles de IA',
    rightClickInfoLoading: 'Generando información...',
    rightClickInfoClose: 'Cerrar',
    rightClickSpecialtyHint: 'Clic derecho para aprender más sobre esta especialidad',
    rightClickProblemHint: 'Clic derecho para aprender más sobre este problema',
    rightClickCounselingHint: 'Clic derecho para aprender más sobre este tipo de consejería',
    learnMore: 'Aprender más sobre',
    password: 'Contrasena',
    confirmPassword: 'Confirmar Contrasena',
    forgotPassword: 'Olvido / Cambiar Contrasena',
    resetPassword: 'Restablecer Contrasena',
    sendResetLink: 'Enviar enlace de restablecimiento',
    resetEmailSent: 'Correo de restablecimiento enviado! Revise su bandeja de entrada.',
    newPassword: 'Nueva Contrasena',
    passwordMinLength: 'La contrasena debe tener al menos 8 caracteres',
    passwordMismatch: 'Las contrasenas no coinciden',
    invalidCredentials: 'Correo o contrasena invalidos',
    setYourPassword: 'Establezca su contrasena',
    passwordUpdated: 'Contrasena actualizada exitosamente!',
    checkYourEmail: 'Revise su correo para el enlace de restablecimiento',
    backToSignIn: 'Volver a Iniciar Sesion',
    signInWithEmail: 'Iniciar sesion con correo y contrasena',
    createAccountWithPassword: 'Crear cuenta con correo y contrasena',
    enterPassword: 'Ingrese su contrasena',
    enterNewPassword: 'Ingrese una nueva contrasena',
    confirmNewPassword: 'Confirme su nueva contrasena',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
